### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by Chealer** [EMN-Data/ckan-api-postman#1]
The Setup Instructions in README.md seem to be outdated. If I understand correctly, the datahub.postman_environment.json file in this repository already defines variables such as api-version. But step 3 instructs to download [from getpostman.com](https://www.getpostman.com/collections/6177c70a5ed4d84ae5ac). Should it not instruct instead to download a release of ckan-api-postman?

**Comment by nwunder** [comment]
You are correct. I updated the readme, hopefully that is a little more clear. Thanks!
